apiVersion: v1
kind: Namespace
metadata:
  name: kube-elk

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: kube-elk
  name: elastic-cluster
  labels:
    component: elasticsearch

spec:
  serviceName: elasticsearch
  replicas: 1                      #Required number of replicas

  updateStrategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                # Specific Host will be ES-Nodes.
                - host-10-1-2-71
      securityContext:
        fsGroup: 1000
      initContainers: #will always initialize before other containers
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        #resources:
        #    requests:
        #        memory: 1Gi
        securityContext:
          privileged: true
          runAsUser: 1000
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        env:
        #- name: discovery.type
        #  value: single-node
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: "-Xms4g -Xmx4g"
          #"-Xms512m -Xmx512m"
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
        # Image Tag Version => https://www.docker.elastic.co/
        #imagePullPolicy: Always
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
        volumeMounts:
        - name: vl-es-data
          mountPath: "/usr/share/elasticsearch/data"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
      volumes:
      - name: vl-es-data
        hostPath:
          # ES data will store at Local DISK! - You have to Create and set permission!! (chown 1000...)
          path: "/opt/elastic"
          type: DirectoryOrCreate

---
# For Serving
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-client
  namespace: kube-elk
  #labels:
  #  component: elasticsearch
spec:
  type: LoadBalancer
  selector:
    component: elasticsearch
  ports:
  - name: http
    port: 9200
    protocol: TCP
---
# You can check cluster health with this URL
# > http://elasticsearch-client.kube-elk:9200/_cluster/health?pretty
