apiVersion: v1
kind: ReplicationController
metadata:
  name: elk-kibana
  namespace: kube-elk
spec:
  replicas: 1
  selector:
    name: elk-kibana
  template:
    metadata:
      labels:
        name: elk-kibana
    spec:
      containers:
      - name: kibana
        env:
        - name: discovery.type
          value: single-node
        - name: SERVER_NAME
          value: kibana.test.hcdd.kr
        - name: ELASTICSEARCH_URL
          #ELASTICSEARCH_HOSTS <- for 7.x
          #ELASTICSEARCH_URL <- for 6.x
          value: "http://elasticsearch-client.kube-elk:9200"
        image: docker.elastic.co/kibana/kibana:6.6.0
        # Image Tag Version => https://www.docker.elastic.co/
        ports:
        - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: elk-kibana
  namespace: kube-elk
  labels:
    name: elk-kibana
spec:
  type: LoadBalancer
  selector:
    name: elk-kibana
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
    name: kibana-port
