---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: apm-server-config
  labels:
    k8s-app: apm-server
data:
  apm-server.yml: |-
    name: ${NODE_NAME}
    apm-server:
      host: "0.0.0.0:8200"
    setup.template.settings:
      index:
        number_of_shards: 1
        codec: best_compression
    setup.dashboards.enabled: true
    setup.kibana:
            host: "elk-kibana.kube-elk:5601"
    output.elasticsearch:
      hosts: ['elasticsearch-client.kube-elk:9200']
      indices:
        - index: "apm-%{[beat.version]}-sourcemap"
          when.contains:
            processor.event: "sourcemap"
        - index: "apm-%{[beat.version]}-error-%{+yyyy.MM.dd}"
          when.contains:
            processor.event: "error"
        - index: "apm-%{[beat.version]}-transaction-%{+yyyy.MM.dd}"
          when.contains:
            processor.event: "transaction"
        - index: "apm-%{[beat.version]}-span-%{+yyyy.MM.dd}"
          when.contains:
            processor.event: "span"
---
apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: kube-system
  labels:
    app: apm-server
spec:
  type: LoadBalancer
  selector:
    app: apm-server
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200
    name: apm-port
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kube-system
  name: apm-server
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      containers:
      - name: apm-server
        image: docker.elastic.co/apm/apm-server:6.6.0
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 8200
          name: apm-port
        volumeMounts:
        - name: apm-server-config
          mountPath: /usr/share/apm-server/apm-server.yml
          readOnly: true
          subPath: apm-server.yml
      volumes:
      - name: apm-server-config
        configMap:
          name: apm-server-config
